server:
    port: 8090

spring:
    application:
        name: "associados"
    data:
        mongodb:
            authentication-database: admin
            username: rootuser
            password: rootpass
            database: avaliacaoiv
            port: 27017
            host: localhost
            auto-index-creation: true
    mvc: 
        pathmatch: 
            matching-strategy: ant-path-matcher


eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
